-- MySQL Script generated by MySQL Workbench
-- Mon Sep 11 20:20:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema christian_arana
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema christian_arana
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `christian_arana` ;
USE `christian_arana` ;

-- -----------------------------------------------------
-- Table `christian_arana`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `christian_arana`.`employees` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `age` INT NULL,
  `birth_date` DATE NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `job_tittle` VARCHAR(50) NULL,
  `date_modified` TIMESTAMP NOT NULL,
  `date_created` TIMESTAMP NOT NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `christian_arana`.`access_levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `christian_arana`.`access_levels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employees_employee_id` INT NOT NULL,
  `access_level` INT NOT NULL DEFAULT 0,
  `description` VARCHAR(255) NULL,
  `date_modified` TIMESTAMP NOT NULL,
  `date_created` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_access_levels_employees1_idx` (`employees_employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_access_levels_employees1`
    FOREIGN KEY (`employees_employee_id`)
    REFERENCES `christian_arana`.`employees` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
